apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /logout
  name: talenteo-logout-ingress
spec:
  tls:
  - hosts:
    - 'int.talenteo.com'
    secretName: int-talenteo-com-tls
  rules:
  - host: int.talenteo.com
    http:
      paths:
      - path: /logout(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: talenteo-ui-helm-int
            port: 
              number: 80